import static java.lang.Thread.sleep;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import java.util.Locale;


/**
 *
 * @author EXPER
 */
public class film_ekrani extends javax.swing.JFrame {

    Girisekrani g = new Girisekrani();
    static kullanici_islemleri k = new kullanici_islemleri();
    
    static int puan=0;
    
    static int milliseconds = 0;
    static int seconds = 0;
    static int minutes ;
    static int hours = 0;
    
    static boolean state = true;
    static String tut;
    static String filmad;
    static boolean izlenmismi = false;

     
    
     public film_ekrani() {
        initComponents();
         
      
    }
     public void yap(){
             
              
        filmad = jTextField_filmisim.getText();
        minutes=k.suregetir(filmad);
        System.out.println(minutes);
        izlemesuresi_.setText(hours+": "+minutes+": "+seconds);
        
        
      
        if(minutes!=0)
            izlenmismi=true;
            izlemetarihi_.setText(k.tarihgetir(filmad));
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_filmisim = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        geributon = new javax.swing.JButton();
        izlemetarihi_ = new javax.swing.JTextField();
        izlemesuresi_ = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));

        jLabel1.setText("Film İsim");

        jLabel2.setText("Film tür");

        jTextField_filmisim.setEditable(false);

        jTextField2.setEditable(false);

        jButton1.setText("İzle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Durdur");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("İzleme tarihi");

        jLabel4.setText("İzlenen süre");

        geributon.setText("Geri");
        geributon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geributonActionPerformed(evt);
            }
        });

        jLabel5.setText("Puan");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Puan Verin", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_filmisim)
                                .addComponent(jTextField2)
                                .addComponent(izlemesuresi_, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(izlemetarihi_)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geributon)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_filmisim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(geributon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(izlemetarihi_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(izlemesuresi_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geributonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geributonActionPerformed
        
        //String filmad = jTextField_filmisim.getText();
            
        try {
            
            if(izlenmismi){
            k.filmkullaniciguncelle(filmad,izlemetarihi_.getText(),minutes); 
                System.out.println("izlemiş");
             
            } else{
               if(minutes!=0)
               k.filmkullaniciekle(filmad,izlemetarihi_.getText(),minutes,puan);
               System.out.println("izlememiş");
            }
          
        } catch (SQLException ex) {
            Logger.getLogger(film_ekrani.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        state = false;
        
          milliseconds=0;
          seconds = 0;
          minutes = 0;
          hours = 0;
          izlemesuresi_.setText(hours+": "+minutes+": "+seconds);
        
        try {
            new programkullanici_ekrani().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(film_ekrani.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.hide();
        
        
        
    }//GEN-LAST:event_geributonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       
        String date = new SimpleDateFormat("dd/MMM/yyyy", Locale.UK).format(new Date());
        izlemetarihi_.setText(date);
      
       
        state = true;
        
        Thread t = new Thread()
        {
         public void run()
            {
                for(;;)
                {
                    if(state==true)
                 {       
                    try
                    {
                        sleep(1);
                      
                        if(milliseconds>1000){
                            milliseconds=0;
                            seconds++;
                        }
                        if(seconds>59){
                            milliseconds=0;
                            seconds=0;
                            minutes++;
                        }
                        if(minutes>59){
                            milliseconds=0;
                            seconds=0;
                            minutes=0;
                            hours++;
                        }
                        milliseconds++;
                        izlemesuresi_.setText(hours+": "+minutes+": "+seconds);
                    }
                     catch(Exception e){
                  }      
               } else
                     break;   
                 
            }  } };
        t.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
       
        state = false;
        tut = hours+":"+minutes+":"+seconds;
        
        System.out.println(tut);
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String str =   jComboBox1.getSelectedItem().toString();
        puan = Integer.parseInt(str);
    }//GEN-LAST:event_jComboBox1ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(film_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(film_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(film_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(film_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
     /* //*/ java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new film_ekrani().setVisible(true);
                
           
              
            }
        });
   
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton geributon;
    public static javax.swing.JTextField izlemesuresi_;
    private javax.swing.JTextField izlemetarihi_;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField_filmisim;
    // End of variables declaration//GEN-END:variables
}
